#!/usr/bin/with-contenv sh
set -e
# Ensure runtime dirs exist
mkdir -p /run/php
chown -R nginx:nginx /run/php

# Prefer the symlink we created; fallback to the real binary
if [ -x /usr/sbin/php-fpm ]; then
  exec /usr/sbin/php-fpm -F
else
  exec /usr/sbin/php-fpm83 -F
fi
